### ISSUE TITLE
Learning About Branches in Class Son??

### ISSUE THREAD

**Issue by dylan-dot-c** [JamarTG/info2180-lab1#1]
Why you up so late in the night??
Anyways Im sure you already knew about branches...

**Comment by JamarTG** [comment]
Yes, we're learning git. And you're probably sabotaging my grade.

**Comment by dylan-dot-c** [comment]
Interesting you are already a straight A student...
This wont affect you

**Comment by dylan-dot-c** [comment]
Ill close the issue later

**Comment by JamarTG** [comment]
I'm not a straight-A student. I already have around 4 zeros in my 3rd week of second year

**Comment by dylan-dot-c** [comment]
Dont worry that wont change the fact that ur a pro
